language: rust
cache: cargo
dist: xenial
sudo: false
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

branches:
  only:
    - master
script:
  - |
    cargo build --verbose &&
    cargo test --verbose
